[build]
  base = "client"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_URL = "https://shreeramdairy.onrender.com"
  VITE_RAZORPAY_KEY_ID = "rzp_test_SwFI9BNT6yF3Ff"
  VITE_GOOGLE_CLIENT_ID = "145880098160-usmgu8tq8uc0q8buvlp0bh2ues8ck68r.apps.googleusercontent.com"

[[redirects]]
  from = "/api/*"
  to = "https://shreeramdairy.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {X-Forwarded-Host = ":host", X-Forwarded-Proto = "https"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
